site_name: Definitions of evaluation criteria for integrated assessment modelling scenarios
site_url: https://iamconsortium.github.io/scenario-evaluation-criteria/
repo_name: scenario-evaluation-criteria
repo_url: https://github.com/IAMconsortium/scenario-evaluation-criteria/
copyright: © 2025 Integrated Assessment Modelling Consortium (IAMC)

nav:
  - Home: index.md
  - Summary: summary.md
  - Components:
    - components/index.md
    - Types: components/types.md
    - Descriptions: components/descriptions.md
    - Thresholds: components/thresholds.md
    - Reference data: components/reference_data.md
    - Sources: components/sources.md
  - Tutorials:
    - tutorials/index.md
    - Raw: tutorials/raw.md
    - R: tutorials/R.py
    - Python: tutorials/python.py
  - Code documentation:
    - R: code/R.md
    - Python: code/python.md

theme:
  features:
  - content.tabs.link
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.path
  - navigation.indexes
  - navigation.expand
  - toc.integrate
  logo: assets/logos/logo.svg
  favicon: assets/logos/favicon.ico
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

markdown_extensions:
- admonition
- attr_list
- md_in_html
- tables
- pymdownx.superfences
- pymdownx.details
- pymdownx.tabbed:
    alternate_style: yes
- pymdownx.snippets:
    base_path: docs
- pymdownx.arithmatex:
    generic: yes
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/extra.css
  - assets/css/theme-toggle.css

plugins:
  - search
  - macros:
      module_name: scripts/mkdocs_macros
  - include-markdown
  - markdown-exec
  - mkdocs-jupyter:
      execute: True
      include_requirejs: True
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            show_source: True
            members_order: source
            merge_init_into_class: True
            separate_signature: True
            docstring_style: numpy
            filters: ["!^_"]
          paths: [python]
